name: Publish

on:
  push:
    branches:
      - src

jobs:
  build-n-deploy:
    name: Build and Deploy
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '13.7'

    - name: Install
      uses: nuxt/actions-yarn@master
      with:
        args: install

    - name: Build
      uses: nuxt/actions-yarn@master
      with:
        args: run build

    - name: 'Deploy into GitHub-Pages'
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
